name: Gitleaks Secret Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 4 * * *'

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
        with:
          args: detect --source . --no-git --redact --report-format sarif --report-path gitleaks.sarif --config .gitleaks.toml
      - name: Show report status
        run: |
          if [ -f gitleaks.sarif ]; then
            echo "Gitleaks SARIF generated";
            wc -c gitleaks.sarif || true;
          else
            echo "No SARIF file generated (likely no findings).";
          fi
      - name: Upload SARIF to GitHub Security tab
        if: always() && hashFiles('gitleaks.sarif') != ''
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: gitleaks.sarif
